[project]
name = "hepz-grind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "discord-py>=2.5.2",
    "python-dotenv>=1.1.1",
]
